### ISSUE TITLE
About the network's trained model

### ISSUE THREAD

**Issue by small-beebee** [jiwei0921/DCF#1]
First of all, thank you very much for your outstanding contribution. But I have a request, I hope you can upload the weights trained on the NJUD+NLPR dataset, because I can't reproduce the results of your version. If you can do this, I would be very grateful！

**Comment by jiwei0921** [comment]
Thanks very much for your attention and question. I'm not sure what your GPU environment is, but generally using the default configuration will not make much difference in performance. The only major concern point, probably in phase 1, was that the checkpoint generated was not optimal for phase 2. This may have made a difference in performance. You can try using multiple Checkpoint initialization for phase 2, or let him train for a long time.

Happy to share our work with you, an available checkpoint has updated in our Github.
